apiVersion: v1
kind: Service
metadata:
  name: mysql-public-port-access
  namespace: ns-deploy
spec:
  selector:
    app: projeto-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
