apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database
  namespace: ns-deploy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/host/d/git/dio-projeto-aplicacao/k8s-projeto1-app-base/data